#!/usr/bin/env python3
"""Snapshot the column definitions of cBioPortal's ClickHouse tables.

The system prompt documents the core schema as authoritative, so the tests
cross-check it against the real DDL. That DDL lives in the cbioportal repo;
this script copies every CREATE TABLE column block and ORDER BY key into
tests/fixtures/cbioportal_clickhouse_ddl.sql so the tests run without a
cbioportal checkout.

Outputs:
  - tests/fixtures/cbioportal_clickhouse_ddl.sql

Usage:
  python scripts/extract_clickhouse_ddl.py /path/to/cbioportal
"""

import os
import re
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
OUTPUT = os.path.join(PROJECT_ROOT, "tests", "fixtures", "cbioportal_clickhouse_ddl.sql")

DDL_FILES = (
    "src/main/resources/db-scripts/clickhouse/init/schema.sql",
    "src/main/resources/db-scripts/clickhouse/clickhouse.sql",
)

# CREATE TABLE name ( <columns> ) ENGINE ... [ORDER BY <key>] ... ;
CREATE_TABLE_RE = re.compile(
    r"CREATE TABLE (?:IF NOT EXISTS )?`?(\w+)`?\s*\((.*?)\)\s*ENGINE([^;]*)", re.S | re.I
)
ORDER_BY_RE = re.compile(r"ORDER BY\s+(\([^)]*\)|\w+(?:\(\))?)", re.I)


def extract(cbioportal_root: str) -> str:
    commit = (
        subprocess.run(
            ["git", "rev-parse", "HEAD"], capture_output=True, text=True, cwd=cbioportal_root
        ).stdout.strip()
        or "unknown"
    )
    parts = [
        "-- Generated by scripts/extract_clickhouse_ddl.py — do not edit by hand.",
        f"-- Source: cBioPortal/cbioportal@{commit}",
        "",
    ]
    for rel in DDL_FILES:
        with open(os.path.join(cbioportal_root, rel), encoding="utf-8") as f:
            text = f.read()
        for name, columns, engine in CREATE_TABLE_RE.findall(text):
            parts.append(f"-- {rel}")
            order_by = ORDER_BY_RE.search(engine)
            key = f"\nORDER BY {' '.join(order_by.group(1).split())}" if order_by else ""
            parts.append(f"CREATE TABLE {name} ({columns.rstrip()}\n){key};")
            parts.append("")
    return "\n".join(parts)


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(extract(sys.argv[1]))
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
