#!/usr/bin/env python3
"""Fetch OncoTree tumor types and generate oncotree.json + SQL migration.

Outputs:
  - src/cbioportal_mcp/resources/oncotree.json  (compact, ~120KB)
  - sql/add-oncotree-fields.sql                 (ClickHouse migration)

Usage:
  python scripts/update_oncotree.py
"""

import json
import os
import sys
import urllib.request

ONCOTREE_API_URL = (
    "https://oncotree.info/api/tumorTypes?version=oncotree_latest_stable"
)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
JSON_OUTPUT = os.path.join(
    PROJECT_ROOT, "src", "cbioportal_mcp", "resources", "oncotree.json"
)
SQL_OUTPUT = os.path.join(PROJECT_ROOT, "sql", "add-oncotree-fields.sql")

KEEP_FIELDS = (
    "code",
    "name",
    "mainType",
    "tissue",
    "parent",
    "level",
    "revocations",
    "precursors",
)


def fetch_oncotree() -> list[dict]:
    """Fetch tumor types from the OncoTree API."""
    print(f"Fetching {ONCOTREE_API_URL} ...")
    req = urllib.request.Request(
        ONCOTREE_API_URL,
        headers={"Accept": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    print(f"  Got {len(data)} tumor types")
    return data


def trim_entry(entry: dict) -> dict:
    """Keep only the fields we need, lowering the code for matching."""
    out = {}
    for field in KEEP_FIELDS:
        val = entry.get(field)
        if field in ("revocations", "precursors"):
            # Ensure list, filter empty
            if isinstance(val, list) and val:
                out[field] = val
        elif val is not None and val != "":
            out[field] = val
    return out


def write_json(entries: list[dict]) -> None:
    """Write compact oncotree.json."""
    os.makedirs(os.path.dirname(JSON_OUTPUT), exist_ok=True)
    with open(JSON_OUTPUT, "w", encoding="utf-8") as f:
        json.dump(entries, f, separators=(",", ":"), ensure_ascii=False)
    size_kb = os.path.getsize(JSON_OUTPUT) / 1024
    print(f"  Wrote {JSON_OUTPUT} ({size_kb:.0f} KB, {len(entries)} entries)")


def sql_escape(s: str) -> str:
    """Escape a string for ClickHouse SQL."""
    return s.replace("\\", "\\\\").replace("'", "\\'")


def write_sql(entries: list[dict]) -> None:
    """Write ClickHouse migration SQL for OncoTree fields on type_of_cancer."""
    os.makedirs(os.path.dirname(SQL_OUTPUT), exist_ok=True)

    lines = [
        "-- ============================================================================",
        "-- OncoTree fields for type_of_cancer",
        "-- ============================================================================",
        "-- Generated by scripts/update_oncotree.py",
        "-- Adds mainType, tissue, level, revocations, precursors columns so the LLM",
        "-- can resolve deprecated codes and navigate the OncoTree hierarchy.",
        "-- Run AFTER the base cBioPortal schema is loaded.",
        "-- ============================================================================",
        "",
        "-- New columns",
        "ALTER TABLE type_of_cancer ADD COLUMN IF NOT EXISTS main_type String;",
        "ALTER TABLE type_of_cancer ADD COLUMN IF NOT EXISTS tissue String;",
        "ALTER TABLE type_of_cancer ADD COLUMN IF NOT EXISTS level UInt8;",
        "ALTER TABLE type_of_cancer ADD COLUMN IF NOT EXISTS revocations Array(String);",
        "ALTER TABLE type_of_cancer ADD COLUMN IF NOT EXISTS precursors Array(String);",
        "",
        "-- Column comments",
        "ALTER TABLE type_of_cancer MODIFY COLUMN main_type String"
        "  COMMENT 'Broad OncoTree grouping (e.g. Non-Small Cell Lung Cancer, Glioma). Useful for grouping related subtypes.';",
        "ALTER TABLE type_of_cancer MODIFY COLUMN tissue String"
        "  COMMENT 'Tissue of origin (e.g. Lung, CNS/Brain, Breast). Top-level anatomical grouping.';",
        "ALTER TABLE type_of_cancer MODIFY COLUMN level UInt8"
        "  COMMENT 'Depth in OncoTree hierarchy: 1 = tissue, 2-6 = increasingly specific subtypes. Lower = broader.';",
        "ALTER TABLE type_of_cancer MODIFY COLUMN revocations Array(String)"
        "  COMMENT 'Deprecated OncoTree codes that this code replaces (e.g. BLL replaces ALL, GB replaces GBM). Search here when a user code is not found.';",
        "ALTER TABLE type_of_cancer MODIFY COLUMN precursors Array(String)"
        "  COMMENT 'Previous codes merged into this code (e.g. CLLSLL merges CLL and SLL). Similar to revocations but for code merges.';",
        "",
        "-- Populate from OncoTree data",
    ]

    update_lines = []
    for entry in entries:
        code = entry.get("code", "").lower()
        if not code:
            continue

        main_type = entry.get("mainType", "")
        tissue = entry.get("tissue", "")
        level = entry.get("level")
        revocations = entry.get("revocations", [])
        precursors = entry.get("precursors", [])

        # Always set main_type, tissue, level for every entry
        sets = []
        if main_type:
            sets.append(f"main_type = '{sql_escape(main_type)}'")
        if tissue:
            sets.append(f"tissue = '{sql_escape(tissue)}'")
        if level is not None:
            sets.append(f"level = {int(level)}")
        if revocations:
            arr = ", ".join(f"'{sql_escape(r)}'" for r in revocations)
            sets.append(f"revocations = [{arr}]")
        if precursors:
            arr = ", ".join(f"'{sql_escape(p)}'" for p in precursors)
            sets.append(f"precursors = [{arr}]")

        if sets:
            update_lines.append(
                f"ALTER TABLE type_of_cancer UPDATE {', '.join(sets)} "
                f"WHERE type_of_cancer_id = '{sql_escape(code)}';"
            )

    lines.extend(update_lines)
    lines.append("")

    with open(SQL_OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"  Wrote {SQL_OUTPUT} ({len(update_lines)} UPDATE statements)")


def main() -> None:
    raw = fetch_oncotree()
    entries = [trim_entry(e) for e in raw]
    # Sort by code for deterministic output
    entries.sort(key=lambda e: e.get("code", ""))
    write_json(entries)
    write_sql(entries)
    print("Done.")


if __name__ == "__main__":
    main()
