-- Generated by scripts/extract_clickhouse_ddl.py — do not edit by hand.
-- Source: cBioPortal/cbioportal@5677496c44def7693ffd5c9634d3c8ce3aa4b7c2

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE allele_specific_copy_number (
    `mutation_event_id` Int64,
    `genetic_profile_id` Int64,
    `sample_id` Int64,
    `ascn_integer_copy_number` Nullable(Int64),
    `ascn_method` String,
    `ccf_expected_copies_upper` Nullable(Float64),
    `ccf_expected_copies` Nullable(Float64),
    `clonal` Nullable(String),
    `minor_copy_number` Nullable(Int64),
    `expected_alt_copies` Nullable(Int64),
    `total_copy_number` Nullable(Int64)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE alteration_driver_annotation (
    `alteration_event_id` Int64,
    `genetic_profile_id` Int64,
    `sample_id` Int64,
    `driver_filter` Nullable(String),
    `driver_filter_annotation` Nullable(String),
    `driver_tiers_filter` Nullable(String),
    `driver_tiers_filter_annotation` Nullable(String)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE authorities (
    `email` String,
    `authority` String
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE cancer_study (
    `cancer_study_id` Int64,
    `cancer_study_identifier` Nullable(String),
    `type_of_cancer_id` String,
    `name` String,
    `description` String,
    `public` Int32,
    `pmid` Nullable(String),
    `citation` Nullable(String),
    `groups` Nullable(String),
    `status` Nullable(Int64),
    `import_date` Nullable(DateTime64(6)),
    `reference_genome_id` Nullable(Int64)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE cancer_study_tags (
    `cancer_study_id` Int64,
    `tags` String
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE clinical_attribute_meta (
    `attr_id` String,
    `display_name` String,
    `description` String,
    `datatype` String,
    `patient_attribute` Int32,
    `priority` String,
    `cancer_study_id` Int64
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE clinical_event (
    `clinical_event_id` Int64,
    `patient_id` Int64,
    `start_date` Int64,
    `stop_date` Nullable(Int64),
    `event_type` String
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE clinical_event_data (
    `clinical_event_id` Int64,
    `key` String,
    `value` String
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE clinical_patient (
    `internal_id` Int64,
    `attr_id` String,
    `attr_value` String
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE clinical_sample (
    `internal_id` Int64,
    `attr_id` String,
    `attr_value` String
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE cna_event (
    `cna_event_id` Int64,
    `entrez_gene_id` Int64,
    `alteration` Int32
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE copy_number_seg (
    `seg_id` Int64,
    `cancer_study_id` Int64,
    `sample_id` Int64,
    `chr` String,
    `start` Int64,
    `end` Int64,
    `num_probes` Int64,
    `segment_mean` Float64
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE copy_number_seg_file (
    `seg_file_id` Int64,
    `cancer_study_id` Int64,
    `reference_genome_id` String,
    `description` String,
    `filename` String
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE data_access_tokens (
    `token` String,
    `username` String,
    `expiration` DateTime64(6),
    `creation` DateTime64(6)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE gene (
    `entrez_gene_id` Int64,
    `hugo_gene_symbol` String,
    `genetic_entity_id` Int64,
    `type` Nullable(String)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE gene_alias (
    `entrez_gene_id` Int64,
    `gene_alias` String
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE gene_panel (
    `internal_id` Int64,
    `stable_id` String,
    `description` Nullable(String)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE gene_panel_list (
    `internal_id` Int64,
    `gene_id` Int64
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE generic_entity_properties (
    `id` Int64,
    `genetic_entity_id` Int64,
    `name` String,
    `value` String
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE geneset (
    `id` Int64,
    `genetic_entity_id` Int64,
    `external_id` String,
    `name` String,
    `description` String,
    `ref_link` Nullable(String)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE geneset_gene (
    `geneset_id` Int64,
    `entrez_gene_id` Int64
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE geneset_hierarchy_leaf (
    `node_id` Int64,
    `geneset_id` Int64
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE geneset_hierarchy_node (
    `node_id` Int64,
    `node_name` String,
    `parent_id` Nullable(Int64)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE genetic_alteration (
    `genetic_profile_id` Int64,
    `genetic_entity_id` Int64,
    `values` String
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE genetic_entity (
    `id` Int64,
    `entity_type` String,
    `stable_id` Nullable(String)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE genetic_profile (
    `genetic_profile_id` Int64,
    `stable_id` String,
    `cancer_study_id` Int64,
    `genetic_alteration_type` String,
    `generic_assay_type` Nullable(String),
    `datatype` String,
    `name` String,
    `description` Nullable(String),
    `show_profile_in_analysis_tab` Int32,
    `pivot_threshold` Nullable(Float64),
    `sort_order` Nullable(String),
    `patient_level` Nullable(Int32)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE genetic_profile_link (
    `referring_genetic_profile_id` Int64,
    `referred_genetic_profile_id` Int64,
    `reference_type` Nullable(String)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE genetic_profile_samples (
    `genetic_profile_id` Int64,
    `ordered_sample_list` String
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE gistic (
    `gistic_roi_id` Int64,
    `cancer_study_id` Int64,
    `chromosome` Int64,
    `cytoband` String,
    `wide_peak_start` Int64,
    `wide_peak_end` Int64,
    `q_value` Float64,
    `amp` Int32
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE gistic_to_gene (
    `gistic_roi_id` Int64,
    `entrez_gene_id` Int64
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE info (
    `db_schema_version` Nullable(String),
    `geneset_version` Nullable(String),
    `derived_table_schema_version` Nullable(String),
    `gene_table_version` Nullable(String)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE mut_sig (
    `cancer_study_id` Int64,
    `entrez_gene_id` Int64,
    `rank` Int64,
    `NumBasesCovered` Int64,
    `NumMutations` Int64,
    `p_value` Float64,
    `q_value` Float64
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE mutation (
    `mutation_event_id` Int64 COMMENT 'References mutation_event.mutation_event_id.',
    `genetic_profile_id` Int64 COMMENT 'References genetic_profile.genetic_profile_id.',
    `sample_id` Int64 COMMENT 'References sample.internal_id.',
    `entrez_gene_id` Int64 COMMENT 'References gene.entrez_gene_id.',
    `center` Nullable(String) COMMENT 'Center where sequencing was performed.',
    `sequencer` Nullable(String) COMMENT 'Sequencing platform used.',
    `mutation_status` Nullable(String) COMMENT 'Mutation status: Germline,
    Somatic,
    or LOH.',
    `validation_status` Nullable(String) COMMENT 'Validation status.',
    `tumor_seq_allele1` Nullable(String) COMMENT 'Tumor allele 1 sequence.',
    `tumor_seq_allele2` Nullable(String) COMMENT 'Tumor allele 2 sequence.',
    `matched_norm_sample_barcode` Nullable(String) COMMENT 'Matched normal sample barcode.',
    `match_norm_seq_allele1` Nullable(String) COMMENT 'Matched normal allele 1 sequence.',
    `match_norm_seq_allele2` Nullable(String) COMMENT 'Matched normal allele 2 sequence.',
    `tumor_validation_allele1` Nullable(String) COMMENT 'Tumor validation allele 1 sequence.',
    `tumor_validation_allele2` Nullable(String) COMMENT 'Tumor validation allele 2 sequence.',
    `match_norm_validation_allele1` Nullable(String) COMMENT 'Matched normal validation allele 1.',
    `match_norm_validation_allele2` Nullable(String) COMMENT 'Matched normal validation allele 2.',
    `verification_status` Nullable(String) COMMENT 'Verification status.',
    `sequencing_phase` Nullable(String) COMMENT 'Sequencing phase.',
    `sequence_source` String COMMENT 'Source of sequencing data.',
    `validation_method` Nullable(String) COMMENT 'Validation method used.',
    `score` Nullable(String) COMMENT 'Score or quality metric.',
    `bam_file` Nullable(String) COMMENT 'Associated BAM file.',
    `tumor_alt_count` Nullable(Int64) COMMENT 'Tumor alternate allele count.',
    `tumor_ref_count` Nullable(Int64) COMMENT 'Tumor reference allele count.',
    `normal_alt_count` Nullable(Int64) COMMENT 'Normal alternate allele count.',
    `normal_ref_count` Nullable(Int64) COMMENT 'Normal reference allele count.',
    `amino_acid_change` Nullable(String) COMMENT 'Amino acid change from mutation.',
    `annotation_json` Nullable(String) COMMENT 'JSON-formatted annotations.'
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE mutation_count_by_keyword (
    `genetic_profile_id` Int64,
    `keyword` Nullable(String),
    `entrez_gene_id` Int64,
    `keyword_count` Int64,
    `gene_count` Int64
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE mutation_event (
    `mutation_event_id` Int64,
    `entrez_gene_id` Int64,
    `chr` Nullable(String),
    `start_position` Nullable(Int64),
    `end_position` Nullable(Int64),
    `reference_allele` Nullable(String),
    `tumor_seq_allele` Nullable(String),
    `protein_change` Nullable(String),
    `mutation_type` Nullable(String),
    `ncbi_build` Nullable(String),
    `strand` Nullable(String),
    `variant_type` Nullable(String),
    `db_snp_rs` Nullable(String),
    `db_snp_val_status` Nullable(String),
    `refseq_mrna_id` Nullable(String),
    `codon_change` Nullable(String),
    `uniprot_accession` Nullable(String),
    `protein_pos_start` Nullable(Int64),
    `protein_pos_end` Nullable(Int64),
    `canonical_transcript` Nullable(Int32),
    `keyword` Nullable(String)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE patient (
    `internal_id` Int64,
    `stable_id` String,
    `cancer_study_id` Int64
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE reference_genome (
    `reference_genome_id` Int64,
    `species` String,
    `name` String,
    `build_name` String,
    `genome_size` Nullable(Int64),
    `url` String,
    `release_date` Nullable(DateTime64(6))
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE reference_genome_gene (
    `entrez_gene_id` Int64,
    `reference_genome_id` Int64,
    `chr` Nullable(String),
    `cytoband` Nullable(String),
    `start` Nullable(Int64),
    `end` Nullable(Int64)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE resource_definition (
    `resource_id` String,
    `display_name` String,
    `description` Nullable(String),
    `resource_type` String,
    `open_by_default` Nullable(Int32),
    `priority` Int64,
    `cancer_study_id` Int64,
    `custom_metadata` Nullable(String)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE resource_patient (
    `internal_id` Int64,
    `resource_id` String,
    `url` String
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE resource_sample (
    `internal_id` Int64,
    `resource_id` String,
    `url` String
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE resource_study (
    `internal_id` Int64,
    `resource_id` String,
    `url` String
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE sample (
    `internal_id` Int64,
    `stable_id` String,
    `sample_type` String,
    `patient_id` Int64
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE sample_cna_event (
    `cna_event_id` Int64 COMMENT 'References cna_event.cna_event_id.',
    `sample_id` Int64 COMMENT 'References sample.internal_id.',
    `genetic_profile_id` Int64 COMMENT 'References genetic_profile.genetic_profile_id.',
    `annotation_json` Nullable(String) COMMENT 'JSON-formatted annotation details.'
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE sample_list (
    `list_id` Int64,
    `stable_id` String,
    `category` String,
    `cancer_study_id` Int64,
    `name` String,
    `description` Nullable(String)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE sample_list_list (
    `list_id` Int64,
    `sample_id` Int64
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE sample_profile (
    `sample_id` Int64,
    `genetic_profile_id` Int64,
    `panel_id` Nullable(Int64)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE structural_variant (
    `internal_id` Int64,
    `genetic_profile_id` Int64,
    `sample_id` Int64,
    `site1_entrez_gene_id` Nullable(Int64),
    `site1_ensembl_transcript_id` Nullable(String),
    `site1_chromosome` Nullable(String),
    `site1_region` Nullable(String),
    `site1_region_number` Nullable(Int64),
    `site1_contig` Nullable(String),
    `site1_position` Nullable(Int64),
    `site1_description` Nullable(String),
    `site2_entrez_gene_id` Nullable(Int64),
    `site2_ensembl_transcript_id` Nullable(String),
    `site2_chromosome` Nullable(String),
    `site2_region` Nullable(String),
    `site2_region_number` Nullable(Int64),
    `site2_contig` Nullable(String),
    `site2_position` Nullable(Int64),
    `site2_description` Nullable(String),
    `site2_effect_on_frame` Nullable(String),
    `ncbi_build` Nullable(String),
    `dna_support` Nullable(String),
    `rna_support` Nullable(String),
    `normal_read_count` Nullable(Int64),
    `tumor_read_count` Nullable(Int64),
    `normal_variant_count` Nullable(Int64),
    `tumor_variant_count` Nullable(Int64),
    `normal_paired_end_read_count` Nullable(Int64),
    `tumor_paired_end_read_count` Nullable(Int64),
    `normal_split_read_count` Nullable(Int64),
    `tumor_split_read_count` Nullable(Int64),
    `annotation` Nullable(String),
    `breakpoint_type` Nullable(String),
    `connection_type` Nullable(String),
    `event_info` Nullable(String),
    `class` Nullable(String),
    `length` Nullable(Int64),
    `comments` Nullable(String),
    `sv_status` String,
    `annotation_json` Nullable(String)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE type_of_cancer (
    `type_of_cancer_id` String,
    `name` String,
    `dedicated_color` String,
    `short_name` Nullable(String),
    `parent` Nullable(String)
);

-- src/main/resources/db-scripts/clickhouse/init/schema.sql
CREATE TABLE users (
    `email` String,
    `name` String,
    `enabled` Int32
);

-- src/main/resources/db-scripts/clickhouse/clickhouse.sql
CREATE TABLE sample_to_gene_panel_derived (
    sample_unique_id String,
    alteration_type LowCardinality(String),
    gene_panel_id LowCardinality(String),
    cancer_study_identifier LowCardinality(String),
    genetic_profile_id LowCardinality(String)
);

-- src/main/resources/db-scripts/clickhouse/clickhouse.sql
CREATE TABLE gene_panel_to_gene_derived (
    gene_panel_id LowCardinality(String),
    gene String
);

-- src/main/resources/db-scripts/clickhouse/clickhouse.sql
CREATE TABLE sample_derived (
    sample_unique_id            String,
    sample_unique_id_base64     String,
    sample_stable_id            String,
    patient_unique_id           String,
    patient_unique_id_base64    String,
    patient_stable_id           String,
    cancer_study_identifier     LowCardinality(String),
    internal_id                 Int,
    -- fields below are needed for the SUMMARY projection
    patient_internal_id         Int,
    sample_type                 String,
    -- fields below are needed for the DETAILED projection
    sequenced                   Int,
    copy_number_segment_present Int
);

-- src/main/resources/db-scripts/clickhouse/clickhouse.sql
CREATE TABLE genomic_event_derived (
    sample_unique_id          String,
    hugo_gene_symbol          String,
    entrez_gene_id            Int32,
    gene_panel_stable_id      LowCardinality(String),
    cancer_study_identifier   LowCardinality(String),
    genetic_profile_stable_id LowCardinality(String),
    variant_type              LowCardinality(String),
    mutation_variant          String,
    mutation_type             LowCardinality(String),
    mutation_status           LowCardinality(String),
    driver_filter             LowCardinality(String),
    driver_filter_annotation  String,
    driver_tiers_filter       LowCardinality(String),
    driver_tiers_filter_annotation String,
    cna_alteration            Nullable(Int8),
    cna_cytoband              String,
    sv_event_info             String,
    patient_unique_id         String,
    off_panel                 Boolean DEFAULT FALSE
);

-- src/main/resources/db-scripts/clickhouse/clickhouse.sql
CREATE TABLE clinical_data_derived (
    internal_id Int,
    sample_unique_id String,
    patient_unique_id String,
    attribute_name LowCardinality(String),
    attribute_value String,
    cancer_study_identifier LowCardinality(String),
    type LowCardinality(String)
);

-- src/main/resources/db-scripts/clickhouse/clickhouse.sql
CREATE TABLE clinical_event_derived (
    `clinical_event_id` Int64,
    `patient_id` Nullable(Int64),
    `patient_stable_id` String,
    `start_date` Nullable(Int64),
    `stop_date` Nullable(Int64),
    `event_type` LowCardinality(String),
    `cancer_study_identifier` LowCardinality(String)
);

-- src/main/resources/db-scripts/clickhouse/clickhouse.sql
CREATE TABLE clinical_event_data_derived (
    patient_unique_id String,
    key String,
    value String,
    start_date Int32,
    stop_date Int32 DEFAULT 0,
    event_type LowCardinality(String),
    cancer_study_identifier LowCardinality(String)
);

-- src/main/resources/db-scripts/clickhouse/clickhouse.sql
CREATE TABLE genetic_alteration_derived (
    sample_unique_id String,
    cancer_study_identifier LowCardinality(String),
    hugo_gene_symbol String,
    profile_type LowCardinality(String),
    alteration_value Nullable(String)
);

-- src/main/resources/db-scripts/clickhouse/clickhouse.sql
CREATE TABLE generic_assay_data_derived (
    sample_unique_id String,
    patient_unique_id String,
    genetic_entity_id String,
    value String,
    generic_assay_type String,
    profile_stable_id String,
    entity_stable_id String,
    datatype String,
    patient_level NUMERIC,
    profile_type String
);

-- src/main/resources/db-scripts/clickhouse/clickhouse.sql
CREATE TABLE mutation_derived (
    molecularProfileId String COMMENT 'Stable ID of the genetic profile',
    sampleId String COMMENT 'Stable ID of the sample',
    sampleInternalId Int64,
    patientId String COMMENT 'Stable ID of the patient',
    entrezGeneId Int64 COMMENT 'Entrez Gene ID from mutation table (NOT NULL)',
    studyId String COMMENT 'Cancer study identifier',
    center Nullable(String) COMMENT 'Sequencing center',
    mutationStatus Nullable(String) COMMENT 'Mutation status (e.g., Somatic, Germline)',
    validationStatus Nullable(String) COMMENT 'Validation status',
    tumorAltCount Nullable(Int64) COMMENT 'Tumor alternate allele count',
    tumorRefCount Nullable(Int64) COMMENT 'Tumor reference allele count',
    normalAltCount Nullable(Int64) COMMENT 'Normal alternate allele count',
    normalRefCount Nullable(Int64) COMMENT 'Normal reference allele count',
    aminoAcidChange Nullable(String) COMMENT 'Amino acid change',
    chr Nullable(String) COMMENT 'Chromosome',
    startPosition Nullable(Int64) COMMENT 'Start position',
    endPosition Nullable(Int64) COMMENT 'End position',
    referenceAllele Nullable(String) COMMENT 'Reference allele',
    tumorSeqAllele Nullable(String) COMMENT 'Tumor sequence allele',
    proteinChange Nullable(String) COMMENT 'Protein change',
    mutationType Nullable(String) COMMENT 'Type of mutation',
    ncbiBuild Nullable(String) COMMENT 'NCBI build version',
    variantType Nullable(String) COMMENT 'Variant type',
    refseqMrnaId Nullable(String) COMMENT 'RefSeq mRNA ID',
    proteinPosStart Nullable(Int64) COMMENT 'Protein position start',
    proteinPosEnd Nullable(Int64) COMMENT 'Protein position end',
    keyword Nullable(String) COMMENT 'Keyword',
    annotationJSON Nullable(String) COMMENT 'Annotation JSON',
    driverFilter Nullable(String) COMMENT 'Driver filter',
    driverFilterAnnotation Nullable(String) COMMENT 'Driver filter annotation',
    driverTiersFilter Nullable(String) COMMENT 'Driver tiers filter',
    driverTiersFilterAnnotation Nullable(String) COMMENT 'Driver tiers filter annotation',
    `GENE.entrezGeneId` Nullable(Int64) COMMENT 'Gene entrez ID',
    `GENE.hugoGeneSymbol` Nullable(String) COMMENT 'HUGO gene symbol',
    `GENE.type` Nullable(String) COMMENT 'Gene type',
    `alleleSpecificCopyNumber.ascnIntegerCopyNumber` Nullable(Int64) COMMENT 'ASCN integer copy number',
    `alleleSpecificCopyNumber.ascnMethod` Nullable(String) COMMENT 'ASCN method',
    `alleleSpecificCopyNumber.ccfExpectedCopiesUpper` Nullable(Float64) COMMENT 'CCF expected copies upper bound',
    `alleleSpecificCopyNumber.ccfExpectedCopies` Nullable(Float64) COMMENT 'CCF expected copies',
    `alleleSpecificCopyNumber.clonal` Nullable(String) COMMENT 'Clonality annotation',
    `alleleSpecificCopyNumber.minorCopyNumber` Nullable(Int64) COMMENT 'Minor copy number',
    `alleleSpecificCopyNumber.expectedAltCopies` Nullable(Int64) COMMENT 'Expected alternate copies',
    `alleleSpecificCopyNumber.totalCopyNumber` Nullable(Int64) COMMENT 'Total copy number'
);

-- src/main/resources/db-scripts/clickhouse/clickhouse.sql
CREATE TABLE generic_assay_profile_entity_derived (
    profile_stable_id LowCardinality(String),
    entity_stable_id  String
);

-- src/main/resources/db-scripts/clickhouse/clickhouse.sql
CREATE TABLE generic_assay_meta_derived (
    entity_stable_id String,
    entity_type LowCardinality(String),
    properties Map(String, String)
);
