-- ============================================================================
-- cancer_study_groups: named cohorts for cross-study aggregation
-- ============================================================================
-- Stores the canonical cBioPortal study groupings so the LLM can query them
-- with a simple JOIN instead of hardcoding study lists.
--
-- Groups defined here:
--   tcga_pan_can_atlas       — the 32 TCGA PanCancer Atlas 2018 studies
--                              (every cancer_study_identifier ending in
--                              _tcga_pan_can_atlas_2018). One sample per
--                              patient, no overlap. Good default for
--                              TCGA-only cross-cancer-type questions.
--   curated_non_redundant    — the 242 manually-curated studies cBioPortal
--                              exposes via --skin.quick_select_buttons.
--                              No overlapping samples across studies. Use
--                              this for the broadest pan-cancer aggregation.
--
-- Refreshed on every clone (DROP + CREATE).
-- ============================================================================

DROP TABLE IF EXISTS cancer_study_groups;

CREATE TABLE cancer_study_groups (
    group_name LowCardinality(String) COMMENT 'Named cohort: tcga_pan_can_atlas | curated_non_redundant',
    cancer_study_identifier String    COMMENT 'cancer_study.cancer_study_identifier — join key'
)
ENGINE = MergeTree
ORDER BY (group_name, cancer_study_identifier)
COMMENT 'Named study cohorts for cross-study aggregation. JOIN on cancer_study_identifier.';

-- tcga_pan_can_atlas: auto-populated from whatever PanCanAtlas studies are loaded
INSERT INTO cancer_study_groups
SELECT 'tcga_pan_can_atlas', cancer_study_identifier
FROM cancer_study
WHERE cancer_study_identifier LIKE '%_tcga_pan_can_atlas_2018';

-- curated_non_redundant: the 242-study list from cBioPortal's
-- --skin.quick_select_buttons "Curated set of non-redundant studies".
-- Hardcoded so this repo owns the definition; studies absent from the
-- current clone simply won't join to any rows downstream.
INSERT INTO cancer_study_groups (group_name, cancer_study_identifier) VALUES
    ('curated_non_redundant', 'acbc_mskcc_2015'),
    ('curated_non_redundant', 'acc_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'acyc_fmi_2014'),
    ('curated_non_redundant', 'acyc_mda_2015'),
    ('curated_non_redundant', 'acyc_mskcc_2013'),
    ('curated_non_redundant', 'acyc_sanger_2013'),
    ('curated_non_redundant', 'all_phase2_target_2018_pub'),
    ('curated_non_redundant', 'all_stjude_2016'),
    ('curated_non_redundant', 'aml_target_2018_pub'),
    ('curated_non_redundant', 'ampca_bcm_2016'),
    ('curated_non_redundant', 'angs_project_painter_2018'),
    ('curated_non_redundant', 'bfn_duke_nus_2015'),
    ('curated_non_redundant', 'blca_bgi'),
    ('curated_non_redundant', 'blca_cornell_2016'),
    ('curated_non_redundant', 'blca_dfarber_mskcc_2014'),
    ('curated_non_redundant', 'blca_mskcc_solit_2012'),
    ('curated_non_redundant', 'blca_mskcc_solit_2014'),
    ('curated_non_redundant', 'blca_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'brca_bccrc'),
    ('curated_non_redundant', 'brca_broad'),
    ('curated_non_redundant', 'brca_igr_2015'),
    ('curated_non_redundant', 'brca_mbcproject_wagle_2017'),
    ('curated_non_redundant', 'brca_metabric'),
    ('curated_non_redundant', 'brca_sanger'),
    ('curated_non_redundant', 'brca_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'ccrcc_irc_2014'),
    ('curated_non_redundant', 'ccrcc_utokyo_2013'),
    ('curated_non_redundant', 'cesc_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'chol_jhu_2013'),
    ('curated_non_redundant', 'chol_nccs_2013'),
    ('curated_non_redundant', 'chol_nus_2012'),
    ('curated_non_redundant', 'chol_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'cll_iuopa_2015'),
    ('curated_non_redundant', 'cllsll_icgc_2011'),
    ('curated_non_redundant', 'coadread_dfci_2016'),
    ('curated_non_redundant', 'coadread_genentech'),
    ('curated_non_redundant', 'coadread_mskcc'),
    ('curated_non_redundant', 'coadread_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'cscc_dfarber_2015'),
    ('curated_non_redundant', 'cscc_hgsc_bcm_2014'),
    ('curated_non_redundant', 'ctcl_columbia_2015'),
    ('curated_non_redundant', 'desm_broad_2015'),
    ('curated_non_redundant', 'dlbc_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'dlbcl_dfci_2018'),
    ('curated_non_redundant', 'dlbcl_duke_2017'),
    ('curated_non_redundant', 'egc_tmucih_2015'),
    ('curated_non_redundant', 'es_dfarber_broad_2014'),
    ('curated_non_redundant', 'es_iocurie_2014'),
    ('curated_non_redundant', 'esca_broad'),
    ('curated_non_redundant', 'esca_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'escc_icgc'),
    ('curated_non_redundant', 'escc_ucla_2014'),
    ('curated_non_redundant', 'gbc_shanghai_2014'),
    ('curated_non_redundant', 'gbm_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'glioma_msk_2018'),
    ('curated_non_redundant', 'hcc_inserm_fr_2015'),
    ('curated_non_redundant', 'hcc_msk_venturaa_2018'),
    ('curated_non_redundant', 'hnsc_broad'),
    ('curated_non_redundant', 'hnsc_jhu'),
    ('curated_non_redundant', 'hnsc_mdanderson_2013'),
    ('curated_non_redundant', 'hnsc_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'kich_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'kirc_bgi'),
    ('curated_non_redundant', 'kirc_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'kirp_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'laml_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'lcll_broad_2013'),
    ('curated_non_redundant', 'lgg_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'lgg_ucsf_2014'),
    ('curated_non_redundant', 'liad_inserm_fr_2014'),
    ('curated_non_redundant', 'lihc_amc_prv'),
    ('curated_non_redundant', 'lihc_riken'),
    ('curated_non_redundant', 'lihc_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'luad_broad'),
    ('curated_non_redundant', 'luad_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'luad_tsp'),
    ('curated_non_redundant', 'lusc_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'mbl_broad_2012'),
    ('curated_non_redundant', 'mbl_pcgp'),
    ('curated_non_redundant', 'mbl_sickkids_2016'),
    ('curated_non_redundant', 'mcl_idibips_2013'),
    ('curated_non_redundant', 'mds_tokyo_2011'),
    ('curated_non_redundant', 'mel_tsam_liang_2017'),
    ('curated_non_redundant', 'meso_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'mixed_allen_2018'),
    ('curated_non_redundant', 'mixed_pipseq_2017'),
    ('curated_non_redundant', 'mm_broad'),
    ('curated_non_redundant', 'mpnst_mskcc'),
    ('curated_non_redundant', 'mrt_bcgsc_2016'),
    ('curated_non_redundant', 'nbl_amc_2012'),
    ('curated_non_redundant', 'nbl_target_2018_pub'),
    ('curated_non_redundant', 'nbl_ucologne_2015'),
    ('curated_non_redundant', 'nccrcc_genentech_2014'),
    ('curated_non_redundant', 'nepc_wcm_2016'),
    ('curated_non_redundant', 'nhl_bcgsc_2011'),
    ('curated_non_redundant', 'nhl_bcgsc_2013'),
    ('curated_non_redundant', 'npc_nusingapore'),
    ('curated_non_redundant', 'nsclc_unito_2016'),
    ('curated_non_redundant', 'ov_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'paac_jhu_2014'),
    ('curated_non_redundant', 'paad_qcmg_uq_2016'),
    ('curated_non_redundant', 'paad_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'paad_utsw_2015'),
    ('curated_non_redundant', 'pact_jhu_2011'),
    ('curated_non_redundant', 'panet_arcnet_2017'),
    ('curated_non_redundant', 'panet_jhu_2011'),
    ('curated_non_redundant', 'panet_shanghai_2013'),
    ('curated_non_redundant', 'pcnsl_mayo_2015'),
    ('curated_non_redundant', 'pcpg_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'pediatric_dkfz_2017'),
    ('curated_non_redundant', 'plmeso_nyu_2015'),
    ('curated_non_redundant', 'prad_broad'),
    ('curated_non_redundant', 'prad_eururol_2017'),
    ('curated_non_redundant', 'prad_fhcrc'),
    ('curated_non_redundant', 'prad_mich'),
    ('curated_non_redundant', 'prad_mpcproject_2018'),
    ('curated_non_redundant', 'prad_mskcc'),
    ('curated_non_redundant', 'prad_mskcc_cheny1_organoids_2014'),
    ('curated_non_redundant', 'prad_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'rms_nih_2014'),
    ('curated_non_redundant', 'rt_target_2018_pub'),
    ('curated_non_redundant', 'sarc_mskcc'),
    ('curated_non_redundant', 'sarc_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'scco_mskcc'),
    ('curated_non_redundant', 'sclc_cancercell_gardner_2017'),
    ('curated_non_redundant', 'sclc_jhu'),
    ('curated_non_redundant', 'sclc_ucologne_2015'),
    ('curated_non_redundant', 'skcm_broad'),
    ('curated_non_redundant', 'skcm_broad_brafresist_2012'),
    ('curated_non_redundant', 'skcm_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'skcm_vanderbilt_mskcc_2015'),
    ('curated_non_redundant', 'skcm_yale'),
    ('curated_non_redundant', 'stad_pfizer_uhongkong'),
    ('curated_non_redundant', 'stad_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'stad_utokyo'),
    ('curated_non_redundant', 'summit_2018'),
    ('curated_non_redundant', 'tet_nci_2014'),
    ('curated_non_redundant', 'tgct_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'thca_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'thym_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'uccc_nih_2017'),
    ('curated_non_redundant', 'ucec_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'ucs_jhu_2014'),
    ('curated_non_redundant', 'ucs_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'um_qimr_2016'),
    ('curated_non_redundant', 'urcc_mskcc_2016'),
    ('curated_non_redundant', 'utuc_mskcc_2015'),
    ('curated_non_redundant', 'uvm_tcga_pan_can_atlas_2018'),
    ('curated_non_redundant', 'vsc_cuk_2018'),
    ('curated_non_redundant', 'wt_target_2018_pub'),
    ('curated_non_redundant', 'acyc_jhu_2016'),
    ('curated_non_redundant', 'prostate_dkfz_2018'),
    ('curated_non_redundant', 'histiocytosis_cobi_msk_2019'),
    ('curated_non_redundant', 'utuc_cornell_baylor_mdacc_2019'),
    ('curated_non_redundant', 'prad_su2c_2019'),
    ('curated_non_redundant', 'cll_broad_2015'),
    ('curated_non_redundant', 'coad_cptac_2019'),
    ('curated_non_redundant', 'brca_mskcc_2019'),
    ('curated_non_redundant', 'acc_2019'),
    ('curated_non_redundant', 'pptc_2019'),
    ('curated_non_redundant', 'prad_msk_2019'),
    ('curated_non_redundant', 'ccrcc_dfci_2019'),
    ('curated_non_redundant', 'mpn_cimr_2013'),
    ('curated_non_redundant', 'nsclc_tracerx_2017'),
    ('curated_non_redundant', 'mnm_washu_2016'),
    ('curated_non_redundant', 'bcc_unige_2016'),
    ('curated_non_redundant', 'coad_caseccc_2015'),
    ('curated_non_redundant', 'metastatic_solid_tumors_mich_2017'),
    ('curated_non_redundant', 'aml_ohsu_2018'),
    ('curated_non_redundant', 'ihch_smmu_2014'),
    ('curated_non_redundant', 'nsclc_mskcc_2018'),
    ('curated_non_redundant', 'skcm_dfci_2015'),
    ('curated_non_redundant', 'skcm_mskcc_2014'),
    ('curated_non_redundant', 'mel_ucla_2016'),
    ('curated_non_redundant', 'utuc_msk_2019'),
    ('curated_non_redundant', 'gbm_columbia_2019'),
    ('curated_non_redundant', 'stad_oncosg_2018'),
    ('curated_non_redundant', 'brca_smc_2018'),
    ('curated_non_redundant', 'luad_oncosg_2020'),
    ('curated_non_redundant', 'angs_painter_2020'),
    ('curated_non_redundant', 'mel_dfci_2019'),
    ('curated_non_redundant', 'lung_smc_2016'),
    ('curated_non_redundant', 'utuc_igbmc_2021'),
    ('curated_non_redundant', 'cscc_ucsf_2021'),
    ('curated_non_redundant', 'chol_icgc_2017'),
    ('curated_non_redundant', 'hccihch_pku_2019'),
    ('curated_non_redundant', 'ihch_ismms_2015'),
    ('curated_non_redundant', 'mbl_dkfz_2017'),
    ('curated_non_redundant', 'pan_origimed_2020'),
    ('curated_non_redundant', 'crc_nigerian_2020'),
    ('curated_non_redundant', 'difg_glass_2019'),
    ('curated_non_redundant', 'pancan_pcawg_2020'),
    ('curated_non_redundant', 'ucec_cptac_2020'),
    ('curated_non_redundant', 'paad_cptac_2021'),
    ('curated_non_redundant', 'lusc_cptac_2021'),
    ('curated_non_redundant', 'luad_cptac_2020'),
    ('curated_non_redundant', 'gbm_cptac_2021'),
    ('curated_non_redundant', 'brca_cptac_2020'),
    ('curated_non_redundant', 'brain_cptac_2020'),
    ('curated_non_redundant', 'mpcproject_broad_2021'),
    ('curated_non_redundant', 'brca_hta9_htan_2022'),
    ('curated_non_redundant', 'lung_nci_2022'),
    ('curated_non_redundant', 'mds_iwg_2022'),
    ('curated_non_redundant', 'biliary_tract_summit_2022'),
    ('curated_non_redundant', 'pog570_bcgsc_2020'),
    ('curated_non_redundant', 'hcc_meric_2021'),
    ('curated_non_redundant', 'prostate_pcbm_swiss_2019'),
    ('curated_non_redundant', 'ucec_ccr_cfdna_msk_2022'),
    ('curated_non_redundant', 'ucec_ccr_msk_2022'),
    ('curated_non_redundant', 'mixed_selpercatinib_2020'),
    ('curated_non_redundant', 'lgsoc_mapk_msk_2022'),
    ('curated_non_redundant', 'mng_utoronto_2021'),
    ('curated_non_redundant', 'blca_bcan_hcrn_2022'),
    ('curated_non_redundant', 'aml_ohsu_2022'),
    ('curated_non_redundant', 'coad_silu_2022'),
    ('curated_non_redundant', 'stmyec_wcm_2022'),
    ('curated_non_redundant', 'bladder_columbia_msk_2018'),
    ('curated_non_redundant', 'sarcoma_msk_2022'),
    ('curated_non_redundant', 'cll_broad_2022'),
    ('curated_non_redundant', 'coadread_cass_2020'),
    ('curated_non_redundant', 'prad_msk_mdanderson_2023'),
    ('curated_non_redundant', 'crc_hta11_htan_2021'),
    ('curated_non_redundant', 'hcc_clca_2024'),
    ('curated_non_redundant', 'brca_fuscc_2020'),
    ('curated_non_redundant', 'brca_dfci_2020'),
    ('curated_non_redundant', 'msk_impact_50k_2026'),
    ('curated_non_redundant', 'chl_sccc_2023'),
    ('curated_non_redundant', 'normal_skin_fibroblast_2024'),
    ('curated_non_redundant', 'normal_skin_keratinocytes_2024'),
    ('curated_non_redundant', 'normal_skin_melanocytes_2024'),
    ('curated_non_redundant', 'ovary_geomx_gray_foundation_2024'),
    ('curated_non_redundant', 'sarcoma_ucla_2024'),
    ('curated_non_redundant', 'crc_sysucc_2022'),
    ('curated_non_redundant', 'ccle_genentech_2014'),
    ('curated_non_redundant', 'sft_sysucc_2023'),
    ('curated_non_redundant', 'luad_cas_2020'),
    ('curated_non_redundant', 'brca_dldccc_2022'),
    ('curated_non_redundant', 'crc_orion_2024'),
    ('curated_non_redundant', 'ccrcc_sjuh_2023'),
    ('curated_non_redundant', 'aml_stjude_2024'),
    ('curated_non_redundant', 'crc_hta8_htan_2024'),
    ('curated_non_redundant', 'angs_painter_2025');
