-- ============================================================================
-- cancer_study_query_preferences: which study (or set of studies) to use
-- for which kind of question
-- ============================================================================
-- One row = "for purpose X, use cancer_study_identifier Y". A preference
-- can name a single study (e.g. treatment_outcomes → msk_chord_2024) or a
-- whole cohort (e.g. pan_cancer_broad → the 242 curated studies). The LLM
-- joins on this table instead of hardcoding study IDs.
--
-- Preferences shipped here:
--   pan_cancer_tcga          32 studies — the TCGA PanCancer Atlas 2018 set
--                            (auto-detected via the _tcga_pan_can_atlas_2018
--                            suffix). One sample per patient, no overlap.
--                            Use for TCGA-only cross-cancer-type questions.
--   pan_cancer_broad        242 studies — cBioPortal's manually-curated
--                            "non-redundant" set (--skin.quick_select_buttons).
--                            No overlapping samples across studies; widest
--                            pan-cancer coverage. Default for "across cancer
--                            types" questions.
--   large_genomic_cohort      1 study  — msk_impact_50k_2026. Biggest single
--                            MSK-IMPACT cohort (~50k samples). Use when the
--                            question is about genomic patterns (mutation
--                            frequency, co-occurrence) at maximum power.
--   treatment_outcomes        1 study  — msk_chord_2024. Rich treatment and
--                            outcomes data in clinical_event_derived. Use
--                            for treatment-related questions.
--
-- Refreshed on every clone (DROP + CREATE). Studies absent from the current
-- clone just won't join to any downstream rows.
-- ============================================================================

DROP TABLE IF EXISTS cancer_study_query_preferences;

CREATE TABLE cancer_study_query_preferences (
    preference_name LowCardinality(String) COMMENT 'Named purpose: pan_cancer_broad | pan_cancer_tcga | large_genomic_cohort | treatment_outcomes',
    cancer_study_identifier String         COMMENT 'cancer_study.cancer_study_identifier — join key',
    notes String                           COMMENT 'Why this study is recommended for this preference'
)
ENGINE = MergeTree
ORDER BY (preference_name, cancer_study_identifier)
COMMENT 'Curated study recommendations per query intent. Lookup by preference_name, then JOIN on cancer_study_identifier.';

-- pan_cancer_tcga: auto-populated from whatever TCGA PanCanAtlas studies are loaded
INSERT INTO cancer_study_query_preferences
SELECT 'pan_cancer_tcga', cancer_study_identifier, 'TCGA PanCancer Atlas 2018'
FROM cancer_study
WHERE cancer_study_identifier LIKE '%_tcga_pan_can_atlas_2018';

-- large_genomic_cohort + treatment_outcomes: single-study recommendations
INSERT INTO cancer_study_query_preferences (preference_name, cancer_study_identifier, notes) VALUES
    ('large_genomic_cohort', 'msk_impact_50k_2026', 'Biggest single MSK-IMPACT cohort; use for max statistical power on genomic patterns (mutation frequency, co-occurrence).'),
    ('treatment_outcomes',   'msk_chord_2024',      'Rich treatment and outcomes data in clinical_event_derived; use for treatment-related cross-cancer questions.');

-- pan_cancer_broad: the 242-study list from cBioPortal's
-- --skin.quick_select_buttons "Curated set of non-redundant studies".
INSERT INTO cancer_study_query_preferences (preference_name, cancer_study_identifier, notes) VALUES
    ('pan_cancer_broad', 'acbc_mskcc_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'acc_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'acyc_fmi_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'acyc_mda_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'acyc_mskcc_2013', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'acyc_sanger_2013', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'all_phase2_target_2018_pub', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'all_stjude_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'aml_target_2018_pub', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ampca_bcm_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'angs_project_painter_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'bfn_duke_nus_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'blca_bgi', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'blca_cornell_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'blca_dfarber_mskcc_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'blca_mskcc_solit_2012', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'blca_mskcc_solit_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'blca_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brca_bccrc', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brca_broad', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brca_igr_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brca_mbcproject_wagle_2017', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brca_metabric', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brca_sanger', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brca_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ccrcc_irc_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ccrcc_utokyo_2013', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'cesc_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'chol_jhu_2013', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'chol_nccs_2013', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'chol_nus_2012', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'chol_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'cll_iuopa_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'cllsll_icgc_2011', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'coadread_dfci_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'coadread_genentech', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'coadread_mskcc', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'coadread_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'cscc_dfarber_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'cscc_hgsc_bcm_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ctcl_columbia_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'desm_broad_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'dlbc_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'dlbcl_dfci_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'dlbcl_duke_2017', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'egc_tmucih_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'es_dfarber_broad_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'es_iocurie_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'esca_broad', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'esca_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'escc_icgc', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'escc_ucla_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'gbc_shanghai_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'gbm_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'glioma_msk_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'hcc_inserm_fr_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'hcc_msk_venturaa_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'hnsc_broad', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'hnsc_jhu', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'hnsc_mdanderson_2013', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'hnsc_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'kich_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'kirc_bgi', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'kirc_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'kirp_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'laml_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'lcll_broad_2013', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'lgg_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'lgg_ucsf_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'liad_inserm_fr_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'lihc_amc_prv', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'lihc_riken', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'lihc_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'luad_broad', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'luad_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'luad_tsp', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'lusc_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mbl_broad_2012', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mbl_pcgp', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mbl_sickkids_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mcl_idibips_2013', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mds_tokyo_2011', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mel_tsam_liang_2017', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'meso_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mixed_allen_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mixed_pipseq_2017', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mm_broad', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mpnst_mskcc', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mrt_bcgsc_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'nbl_amc_2012', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'nbl_target_2018_pub', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'nbl_ucologne_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'nccrcc_genentech_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'nepc_wcm_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'nhl_bcgsc_2011', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'nhl_bcgsc_2013', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'npc_nusingapore', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'nsclc_unito_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ov_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'paac_jhu_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'paad_qcmg_uq_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'paad_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'paad_utsw_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'pact_jhu_2011', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'panet_arcnet_2017', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'panet_jhu_2011', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'panet_shanghai_2013', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'pcnsl_mayo_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'pcpg_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'pediatric_dkfz_2017', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'plmeso_nyu_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'prad_broad', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'prad_eururol_2017', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'prad_fhcrc', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'prad_mich', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'prad_mpcproject_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'prad_mskcc', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'prad_mskcc_cheny1_organoids_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'prad_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'rms_nih_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'rt_target_2018_pub', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'sarc_mskcc', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'sarc_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'scco_mskcc', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'sclc_cancercell_gardner_2017', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'sclc_jhu', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'sclc_ucologne_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'skcm_broad', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'skcm_broad_brafresist_2012', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'skcm_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'skcm_vanderbilt_mskcc_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'skcm_yale', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'stad_pfizer_uhongkong', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'stad_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'stad_utokyo', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'summit_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'tet_nci_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'tgct_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'thca_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'thym_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'uccc_nih_2017', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ucec_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ucs_jhu_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ucs_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'um_qimr_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'urcc_mskcc_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'utuc_mskcc_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'uvm_tcga_pan_can_atlas_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'vsc_cuk_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'wt_target_2018_pub', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'acyc_jhu_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'prostate_dkfz_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'histiocytosis_cobi_msk_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'utuc_cornell_baylor_mdacc_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'prad_su2c_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'cll_broad_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'coad_cptac_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brca_mskcc_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'acc_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'pptc_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'prad_msk_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ccrcc_dfci_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mpn_cimr_2013', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'nsclc_tracerx_2017', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mnm_washu_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'bcc_unige_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'coad_caseccc_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'metastatic_solid_tumors_mich_2017', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'aml_ohsu_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ihch_smmu_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'nsclc_mskcc_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'skcm_dfci_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'skcm_mskcc_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mel_ucla_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'utuc_msk_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'gbm_columbia_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'stad_oncosg_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brca_smc_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'luad_oncosg_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'angs_painter_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mel_dfci_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'lung_smc_2016', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'utuc_igbmc_2021', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'cscc_ucsf_2021', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'chol_icgc_2017', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'hccihch_pku_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ihch_ismms_2015', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mbl_dkfz_2017', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'pan_origimed_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'crc_nigerian_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'difg_glass_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'pancan_pcawg_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ucec_cptac_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'paad_cptac_2021', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'lusc_cptac_2021', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'luad_cptac_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'gbm_cptac_2021', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brca_cptac_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brain_cptac_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mpcproject_broad_2021', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brca_hta9_htan_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'lung_nci_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mds_iwg_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'biliary_tract_summit_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'pog570_bcgsc_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'hcc_meric_2021', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'prostate_pcbm_swiss_2019', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ucec_ccr_cfdna_msk_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ucec_ccr_msk_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mixed_selpercatinib_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'lgsoc_mapk_msk_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'mng_utoronto_2021', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'blca_bcan_hcrn_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'aml_ohsu_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'coad_silu_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'stmyec_wcm_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'bladder_columbia_msk_2018', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'sarcoma_msk_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'cll_broad_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'coadread_cass_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'prad_msk_mdanderson_2023', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'crc_hta11_htan_2021', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'hcc_clca_2024', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brca_fuscc_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brca_dfci_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'msk_impact_50k_2026', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'chl_sccc_2023', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'normal_skin_fibroblast_2024', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'normal_skin_keratinocytes_2024', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'normal_skin_melanocytes_2024', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ovary_geomx_gray_foundation_2024', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'sarcoma_ucla_2024', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'crc_sysucc_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ccle_genentech_2014', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'sft_sysucc_2023', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'luad_cas_2020', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'brca_dldccc_2022', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'crc_orion_2024', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'ccrcc_sjuh_2023', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'aml_stjude_2024', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'crc_hta8_htan_2024', 'cBioPortal curated non-redundant set'),
    ('pan_cancer_broad', 'angs_painter_2025', 'cBioPortal curated non-redundant set');
