-- ============================================================================
-- 4-public-portal-preferences.sql — preferences specific to cbioportal.org
-- ============================================================================
-- These rows describe which studies to use for which kind of question on
-- the *public* cBioPortal deployment. Other deployments should either:
--   1. Delete this file from their image and add their own
--      5-mydeployment-preferences.sql, or
--   2. Leave this file in place — every INSERT below is gated on existence
--      in `cancer_study`, so studies your deployment doesn't have produce
--      zero rows rather than phantom preferences.
--
-- See 3-add-cancer-study-query-preferences.sql for the table schema and
-- the portable, pattern-detected preferences (pan_cancer_tcga).
--
-- Preferences defined here (all defensively existence-checked):
--   all_studies_non_redundant  — the 242-study curated set from cBioPortal's
--                                --skin.quick_select_buttons. Default for
--                                "across cancer types" questions.
--   large_genomic_cohort       — msk_impact_50k_2026. Genomic-pattern
--                                questions at maximum statistical power.
--   treatment_outcomes         — msk_chord_2024. Treatment / outcomes
--                                questions via clinical_event_derived.
-- ============================================================================

-- large_genomic_cohort + treatment_outcomes: single-study recommendations,
-- inserted only if the study is actually loaded.
INSERT INTO cancer_study_query_preferences (preference_name, cancer_study_identifier, notes)
SELECT p.preference_name, p.cancer_study_identifier, p.notes
FROM (
    SELECT 'large_genomic_cohort' AS preference_name,
           'msk_impact_50k_2026'  AS cancer_study_identifier,
           'Biggest single MSK-IMPACT cohort; use for max statistical power on genomic patterns (mutation frequency, co-occurrence).' AS notes
    UNION ALL
    SELECT 'treatment_outcomes',
           'msk_chord_2024',
           'Rich treatment and outcomes data in clinical_event_derived; use for treatment-related cross-cancer questions.'
) p
WHERE p.cancer_study_identifier IN (SELECT cancer_study_identifier FROM cancer_study);

-- all_studies_non_redundant: cBioPortal's manually-curated set of 242
-- studies with no overlapping samples (--skin.quick_select_buttons
-- "Curated set of non-redundant studies"). Only inserts rows for studies
-- present in this clone.
INSERT INTO cancer_study_query_preferences
SELECT 'all_studies_non_redundant', cancer_study_identifier, 'cBioPortal curated non-redundant set'
FROM cancer_study
WHERE cancer_study_identifier IN (
    'acbc_mskcc_2015',
    'acc_tcga_pan_can_atlas_2018',
    'acyc_fmi_2014',
    'acyc_mda_2015',
    'acyc_mskcc_2013',
    'acyc_sanger_2013',
    'all_phase2_target_2018_pub',
    'all_stjude_2016',
    'aml_target_2018_pub',
    'ampca_bcm_2016',
    'angs_project_painter_2018',
    'bfn_duke_nus_2015',
    'blca_bgi',
    'blca_cornell_2016',
    'blca_dfarber_mskcc_2014',
    'blca_mskcc_solit_2012',
    'blca_mskcc_solit_2014',
    'blca_tcga_pan_can_atlas_2018',
    'brca_bccrc',
    'brca_broad',
    'brca_igr_2015',
    'brca_mbcproject_wagle_2017',
    'brca_metabric',
    'brca_sanger',
    'brca_tcga_pan_can_atlas_2018',
    'ccrcc_irc_2014',
    'ccrcc_utokyo_2013',
    'cesc_tcga_pan_can_atlas_2018',
    'chol_jhu_2013',
    'chol_nccs_2013',
    'chol_nus_2012',
    'chol_tcga_pan_can_atlas_2018',
    'cll_iuopa_2015',
    'cllsll_icgc_2011',
    'coadread_dfci_2016',
    'coadread_genentech',
    'coadread_mskcc',
    'coadread_tcga_pan_can_atlas_2018',
    'cscc_dfarber_2015',
    'cscc_hgsc_bcm_2014',
    'ctcl_columbia_2015',
    'desm_broad_2015',
    'dlbc_tcga_pan_can_atlas_2018',
    'dlbcl_dfci_2018',
    'dlbcl_duke_2017',
    'egc_tmucih_2015',
    'es_dfarber_broad_2014',
    'es_iocurie_2014',
    'esca_broad',
    'esca_tcga_pan_can_atlas_2018',
    'escc_icgc',
    'escc_ucla_2014',
    'gbc_shanghai_2014',
    'gbm_tcga_pan_can_atlas_2018',
    'glioma_msk_2018',
    'hcc_inserm_fr_2015',
    'hcc_msk_venturaa_2018',
    'hnsc_broad',
    'hnsc_jhu',
    'hnsc_mdanderson_2013',
    'hnsc_tcga_pan_can_atlas_2018',
    'kich_tcga_pan_can_atlas_2018',
    'kirc_bgi',
    'kirc_tcga_pan_can_atlas_2018',
    'kirp_tcga_pan_can_atlas_2018',
    'laml_tcga_pan_can_atlas_2018',
    'lcll_broad_2013',
    'lgg_tcga_pan_can_atlas_2018',
    'lgg_ucsf_2014',
    'liad_inserm_fr_2014',
    'lihc_amc_prv',
    'lihc_riken',
    'lihc_tcga_pan_can_atlas_2018',
    'luad_broad',
    'luad_tcga_pan_can_atlas_2018',
    'luad_tsp',
    'lusc_tcga_pan_can_atlas_2018',
    'mbl_broad_2012',
    'mbl_pcgp',
    'mbl_sickkids_2016',
    'mcl_idibips_2013',
    'mds_tokyo_2011',
    'mel_tsam_liang_2017',
    'meso_tcga_pan_can_atlas_2018',
    'mixed_allen_2018',
    'mixed_pipseq_2017',
    'mm_broad',
    'mpnst_mskcc',
    'mrt_bcgsc_2016',
    'nbl_amc_2012',
    'nbl_target_2018_pub',
    'nbl_ucologne_2015',
    'nccrcc_genentech_2014',
    'nepc_wcm_2016',
    'nhl_bcgsc_2011',
    'nhl_bcgsc_2013',
    'npc_nusingapore',
    'nsclc_unito_2016',
    'ov_tcga_pan_can_atlas_2018',
    'paac_jhu_2014',
    'paad_qcmg_uq_2016',
    'paad_tcga_pan_can_atlas_2018',
    'paad_utsw_2015',
    'pact_jhu_2011',
    'panet_arcnet_2017',
    'panet_jhu_2011',
    'panet_shanghai_2013',
    'pcnsl_mayo_2015',
    'pcpg_tcga_pan_can_atlas_2018',
    'pediatric_dkfz_2017',
    'plmeso_nyu_2015',
    'prad_broad',
    'prad_eururol_2017',
    'prad_fhcrc',
    'prad_mich',
    'prad_mpcproject_2018',
    'prad_mskcc',
    'prad_mskcc_cheny1_organoids_2014',
    'prad_tcga_pan_can_atlas_2018',
    'rms_nih_2014',
    'rt_target_2018_pub',
    'sarc_mskcc',
    'sarc_tcga_pan_can_atlas_2018',
    'scco_mskcc',
    'sclc_cancercell_gardner_2017',
    'sclc_jhu',
    'sclc_ucologne_2015',
    'skcm_broad',
    'skcm_broad_brafresist_2012',
    'skcm_tcga_pan_can_atlas_2018',
    'skcm_vanderbilt_mskcc_2015',
    'skcm_yale',
    'stad_pfizer_uhongkong',
    'stad_tcga_pan_can_atlas_2018',
    'stad_utokyo',
    'summit_2018',
    'tet_nci_2014',
    'tgct_tcga_pan_can_atlas_2018',
    'thca_tcga_pan_can_atlas_2018',
    'thym_tcga_pan_can_atlas_2018',
    'uccc_nih_2017',
    'ucec_tcga_pan_can_atlas_2018',
    'ucs_jhu_2014',
    'ucs_tcga_pan_can_atlas_2018',
    'um_qimr_2016',
    'urcc_mskcc_2016',
    'utuc_mskcc_2015',
    'uvm_tcga_pan_can_atlas_2018',
    'vsc_cuk_2018',
    'wt_target_2018_pub',
    'acyc_jhu_2016',
    'prostate_dkfz_2018',
    'histiocytosis_cobi_msk_2019',
    'utuc_cornell_baylor_mdacc_2019',
    'prad_su2c_2019',
    'cll_broad_2015',
    'coad_cptac_2019',
    'brca_mskcc_2019',
    'acc_2019',
    'pptc_2019',
    'prad_msk_2019',
    'ccrcc_dfci_2019',
    'mpn_cimr_2013',
    'nsclc_tracerx_2017',
    'mnm_washu_2016',
    'bcc_unige_2016',
    'coad_caseccc_2015',
    'metastatic_solid_tumors_mich_2017',
    'aml_ohsu_2018',
    'ihch_smmu_2014',
    'nsclc_mskcc_2018',
    'skcm_dfci_2015',
    'skcm_mskcc_2014',
    'mel_ucla_2016',
    'utuc_msk_2019',
    'gbm_columbia_2019',
    'stad_oncosg_2018',
    'brca_smc_2018',
    'luad_oncosg_2020',
    'angs_painter_2020',
    'mel_dfci_2019',
    'lung_smc_2016',
    'utuc_igbmc_2021',
    'cscc_ucsf_2021',
    'chol_icgc_2017',
    'hccihch_pku_2019',
    'ihch_ismms_2015',
    'mbl_dkfz_2017',
    'pan_origimed_2020',
    'crc_nigerian_2020',
    'difg_glass_2019',
    'pancan_pcawg_2020',
    'ucec_cptac_2020',
    'paad_cptac_2021',
    'lusc_cptac_2021',
    'luad_cptac_2020',
    'gbm_cptac_2021',
    'brca_cptac_2020',
    'brain_cptac_2020',
    'mpcproject_broad_2021',
    'brca_hta9_htan_2022',
    'lung_nci_2022',
    'mds_iwg_2022',
    'biliary_tract_summit_2022',
    'pog570_bcgsc_2020',
    'hcc_meric_2021',
    'prostate_pcbm_swiss_2019',
    'ucec_ccr_cfdna_msk_2022',
    'ucec_ccr_msk_2022',
    'mixed_selpercatinib_2020',
    'lgsoc_mapk_msk_2022',
    'mng_utoronto_2021',
    'blca_bcan_hcrn_2022',
    'aml_ohsu_2022',
    'coad_silu_2022',
    'stmyec_wcm_2022',
    'bladder_columbia_msk_2018',
    'sarcoma_msk_2022',
    'cll_broad_2022',
    'coadread_cass_2020',
    'prad_msk_mdanderson_2023',
    'crc_hta11_htan_2021',
    'hcc_clca_2024',
    'brca_fuscc_2020',
    'brca_dfci_2020',
    'msk_impact_50k_2026',
    'chl_sccc_2023',
    'normal_skin_fibroblast_2024',
    'normal_skin_keratinocytes_2024',
    'normal_skin_melanocytes_2024',
    'ovary_geomx_gray_foundation_2024',
    'sarcoma_ucla_2024',
    'crc_sysucc_2022',
    'ccle_genentech_2014',
    'sft_sysucc_2023',
    'luad_cas_2020',
    'brca_dldccc_2022',
    'crc_orion_2024',
    'ccrcc_sjuh_2023',
    'aml_stjude_2024',
    'crc_hta8_htan_2024',
    'angs_painter_2025'
);
